site_name: pg_stat_insights - PostgreSQL Performance Monitoring
site_description: Production-ready PostgreSQL extension for query performance monitoring, SQL optimization, and database analytics. Track 52 metrics across 11 views with comprehensive test coverage. Compatible with PostgreSQL 14-17.
site_author: pgelephant
site_url: https://pgelephant.github.io/pg_stat_insights/

repo_name: pgelephant/pg_stat_insights
repo_url: https://github.com/pgelephant/pg_stat_insights
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 pgelephant

# SEO and social media
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pgelephant/pg_stat_insights
      name: pg_stat_insights on GitHub
  generator: false
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: Thanks for your feedback!

theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en
  - tags
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quick-start.md
    - Configuration: configuration.md
  - Features:
    - Views Reference: views.md
    - Metrics Guide: metrics.md
    - Usage Examples: usage.md
  - Advanced:
    - Testing Guide: testing.md
    - CI/CD Workflows: ci-cd.md
    - Troubleshooting: troubleshooting.md
  - Development:
    - Contributing: contributing.md
    - Building from Source: building.md
  - Languages:
    - English: index.md
    - 简体中文: zh_CN/README.md
    - 繁體中文: zh_TW/README.md
    - 日本語: ja_JP/README.md

